"""initial_schema

Revision ID: 659c268ebe0c
Revises: 
Create Date: 2025-12-19 17:06:41.447500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659c268ebe0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('hierarchy_path', sa.String(length=1024), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_is_active'), 'departments', ['is_active'], unique=False)
    op.create_table('budget_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('OPEX', 'CAPEX', name='expensetypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('external_id_1c', sa.String(length=100), nullable=True),
    sa.Column('code_1c', sa.String(length=50), nullable=True),
    sa.Column('is_folder', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['budget_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budget_category_dept_active', 'budget_categories', ['department_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_budget_categories_department_id'), 'budget_categories', ['department_id'], unique=False)
    op.create_index(op.f('ix_budget_categories_external_id_1c'), 'budget_categories', ['external_id_1c'], unique=False)
    op.create_index(op.f('ix_budget_categories_id'), 'budget_categories', ['id'], unique=False)
    op.create_index(op.f('ix_budget_categories_is_active'), 'budget_categories', ['is_active'], unique=False)
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_id_1c', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contractor_dept_active', 'contractors', ['department_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_contractors_department_id'), 'contractors', ['department_id'], unique=False)
    op.create_index(op.f('ix_contractors_external_id_1c'), 'contractors', ['external_id_1c'], unique=False)
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    op.create_index(op.f('ix_contractors_inn'), 'contractors', ['inn'], unique=False)
    op.create_index(op.f('ix_contractors_is_active'), 'contractors', ['is_active'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_id_1c', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.Column('prefix', sa.String(length=10), nullable=True),
    sa.Column('okpo', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status_1c', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_department_id'), 'organizations', ['department_id'], unique=False)
    op.create_index(op.f('ix_organizations_external_id_1c'), 'organizations', ['external_id_1c'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_inn'), 'organizations', ['inn'], unique=False)
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FOUNDER', 'MANAGER', 'ACCOUNTANT', 'HR', 'USER', 'REQUESTER', name='userroleenum'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEBIT', 'CREDIT', name='banktransactiontypeenum'), nullable=False),
    sa.Column('counterparty_name', sa.String(length=500), nullable=True),
    sa.Column('counterparty_inn', sa.String(length=12), nullable=True),
    sa.Column('counterparty_kpp', sa.String(length=9), nullable=True),
    sa.Column('counterparty_account', sa.String(length=20), nullable=True),
    sa.Column('counterparty_bank', sa.String(length=500), nullable=True),
    sa.Column('counterparty_bik', sa.String(length=20), nullable=True),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('business_operation', sa.String(length=100), nullable=True),
    sa.Column('payment_source', sa.Enum('BANK', 'CASH', name='paymentsourceenum'), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('suggested_category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CATEGORIZED', 'MATCHED', 'APPROVED', 'NEEDS_REVIEW', 'IGNORED', name='banktransactionstatusenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_regular_payment', sa.Boolean(), nullable=False),
    sa.Column('regular_payment_pattern_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.Enum('MOSCOW', 'SPB', 'REGIONS', 'FOREIGN', name='regionenum'), nullable=True),
    sa.Column('exhibition', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.Enum('PAYMENT_ORDER', 'CASH_ORDER', 'INVOICE', 'ACT', 'CONTRACT', 'OTHER', name='documenttypeenum'), nullable=True),
    sa.Column('amount_rub_credit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_eur_credit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_rub_debit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_eur_debit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('transaction_month', sa.Integer(), nullable=True),
    sa.Column('transaction_year', sa.Integer(), nullable=True),
    sa.Column('expense_acceptance_month', sa.Integer(), nullable=True),
    sa.Column('expense_acceptance_year', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('import_source', sa.String(length=50), nullable=True),
    sa.Column('import_file_name', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('external_id_1c', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['budget_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_account_number'), 'bank_transactions', ['account_number'], unique=False)
    op.create_index(op.f('ix_bank_transactions_business_operation'), 'bank_transactions', ['business_operation'], unique=False)
    op.create_index(op.f('ix_bank_transactions_category_id'), 'bank_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_counterparty_inn'), 'bank_transactions', ['counterparty_inn'], unique=False)
    op.create_index(op.f('ix_bank_transactions_department_id'), 'bank_transactions', ['department_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_document_number'), 'bank_transactions', ['document_number'], unique=False)
    op.create_index(op.f('ix_bank_transactions_external_id_1c'), 'bank_transactions', ['external_id_1c'], unique=True)
    op.create_index(op.f('ix_bank_transactions_id'), 'bank_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_is_active'), 'bank_transactions', ['is_active'], unique=False)
    op.create_index(op.f('ix_bank_transactions_is_regular_payment'), 'bank_transactions', ['is_regular_payment'], unique=False)
    op.create_index(op.f('ix_bank_transactions_organization_id'), 'bank_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_payment_source'), 'bank_transactions', ['payment_source'], unique=False)
    op.create_index(op.f('ix_bank_transactions_region'), 'bank_transactions', ['region'], unique=False)
    op.create_index(op.f('ix_bank_transactions_status'), 'bank_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_month'), 'bank_transactions', ['transaction_month'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_type'), 'bank_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_year'), 'bank_transactions', ['transaction_year'], unique=False)
    op.create_table('business_operation_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_operation', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_business_op_mapping_unique', 'business_operation_mappings', ['business_operation', 'department_id', 'category_id'], unique=True)
    op.create_index(op.f('ix_business_operation_mappings_business_operation'), 'business_operation_mappings', ['business_operation'], unique=False)
    op.create_index(op.f('ix_business_operation_mappings_category_id'), 'business_operation_mappings', ['category_id'], unique=False)
    op.create_index(op.f('ix_business_operation_mappings_department_id'), 'business_operation_mappings', ['department_id'], unique=False)
    op.create_index(op.f('ix_business_operation_mappings_id'), 'business_operation_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_business_operation_mappings_is_active'), 'business_operation_mappings', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_operation_mappings_is_active'), table_name='business_operation_mappings')
    op.drop_index(op.f('ix_business_operation_mappings_id'), table_name='business_operation_mappings')
    op.drop_index(op.f('ix_business_operation_mappings_department_id'), table_name='business_operation_mappings')
    op.drop_index(op.f('ix_business_operation_mappings_category_id'), table_name='business_operation_mappings')
    op.drop_index(op.f('ix_business_operation_mappings_business_operation'), table_name='business_operation_mappings')
    op.drop_index('ix_business_op_mapping_unique', table_name='business_operation_mappings')
    op.drop_table('business_operation_mappings')
    op.drop_index(op.f('ix_bank_transactions_transaction_year'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_transaction_type'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_transaction_month'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_status'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_region'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_payment_source'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_organization_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_is_regular_payment'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_is_active'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_external_id_1c'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_document_number'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_department_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_counterparty_inn'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_category_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_business_operation'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_account_number'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_inn'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_external_id_1c'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_department_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_contractors_is_active'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_inn'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_external_id_1c'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_department_id'), table_name='contractors')
    op.drop_index('idx_contractor_dept_active', table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_budget_categories_is_active'), table_name='budget_categories')
    op.drop_index(op.f('ix_budget_categories_id'), table_name='budget_categories')
    op.drop_index(op.f('ix_budget_categories_external_id_1c'), table_name='budget_categories')
    op.drop_index(op.f('ix_budget_categories_department_id'), table_name='budget_categories')
    op.drop_index('idx_budget_category_dept_active', table_name='budget_categories')
    op.drop_table('budget_categories')
    op.drop_index(op.f('ix_departments_is_active'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
