"""add vat fields to bank transactions

Revision ID: 5c09cefe54d4
Revises: fbc3e431c429
Create Date: 2025-12-23 15:42:23.836090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c09cefe54d4'
down_revision: Union[str, None] = 'fbc3e431c429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('bank_transactions', sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_transactions', 'vat_rate')
    op.drop_column('bank_transactions', 'vat_amount')
    # ### end Alembic commands ###
