"""add categorization rules table

Revision ID: e05a1f0e0fae
Revises: add_sync_settings
Create Date: 2025-12-21 21:08:43.292746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e05a1f0e0fae'
down_revision: Union[str, None] = 'add_sync_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create categorization_rules table
    op.create_table('categorization_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('rule_type', sa.Enum('COUNTERPARTY_INN', 'COUNTERPARTY_NAME', 'BUSINESS_OPERATION', 'KEYWORD', name='categorizationruletypeenum'), nullable=False),
        sa.Column('counterparty_inn', sa.String(length=20), nullable=True),
        sa.Column('counterparty_name', sa.String(length=500), nullable=True),
        sa.Column('business_operation', sa.String(length=100), nullable=True),
        sa.Column('keyword', sa.String(length=255), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False, server_default='10'),
        sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0.95'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorization_rules_business_operation'), 'categorization_rules', ['business_operation'], unique=False)
    op.create_index(op.f('ix_categorization_rules_category_id'), 'categorization_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_categorization_rules_counterparty_inn'), 'categorization_rules', ['counterparty_inn'], unique=False)
    op.create_index(op.f('ix_categorization_rules_counterparty_name'), 'categorization_rules', ['counterparty_name'], unique=False)
    op.create_index(op.f('ix_categorization_rules_id'), 'categorization_rules', ['id'], unique=False)
    op.create_index(op.f('ix_categorization_rules_is_active'), 'categorization_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_categorization_rules_keyword'), 'categorization_rules', ['keyword'], unique=False)
    op.create_index(op.f('ix_categorization_rules_rule_type'), 'categorization_rules', ['rule_type'], unique=False)

    # Update sync_settings timestamps
    op.alter_column('sync_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # Drop categorization_rules table
    op.drop_index(op.f('ix_categorization_rules_rule_type'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_keyword'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_is_active'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_id'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_counterparty_name'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_counterparty_inn'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_category_id'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_business_operation'), table_name='categorization_rules')
    op.drop_table('categorization_rules')
    # ### end Alembic commands ###
