"""add expense sync fields from 1c

Revision ID: 3281b35e5b80
Revises: 2f3c32cbc2aa
Create Date: 2025-12-24 12:47:15.305456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3281b35e5b80'
down_revision: Union[str, None] = '2f3c32cbc2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('expenses', sa.Column('requester', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.add_column('expenses', sa.Column('is_closed', sa.Boolean(), nullable=False))
    op.add_column('expenses', sa.Column('imported_from_1c', sa.Boolean(), nullable=False))
    op.add_column('expenses', sa.Column('needs_review', sa.Boolean(), nullable=False))
    op.add_column('expenses', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index('ix_expense_payment_date', 'expenses', ['payment_date'], unique=False)
    op.create_index('ix_expense_status_date', 'expenses', ['status', 'request_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expense_status_date', table_name='expenses')
    op.drop_index('ix_expense_payment_date', table_name='expenses')
    op.drop_column('expenses', 'synced_at')
    op.drop_column('expenses', 'needs_review')
    op.drop_column('expenses', 'imported_from_1c')
    op.drop_column('expenses', 'is_closed')
    op.drop_column('expenses', 'is_paid')
    op.drop_column('expenses', 'requester')
    op.drop_column('expenses', 'comment')
    # ### end Alembic commands ###
