"""add expense auto sync settings

Revision ID: 2cf57a21ee11
Revises: 3281b35e5b80
Create Date: 2025-12-24 13:30:02.275796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf57a21ee11'
down_revision: Union[str, None] = '3281b35e5b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_settings', sa.Column('auto_sync_expenses_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sync_settings', sa.Column('sync_expenses_interval_hours', sa.Integer(), nullable=False, server_default='24'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_settings', 'sync_expenses_interval_hours')
    op.drop_column('sync_settings', 'auto_sync_expenses_enabled')
    # ### end Alembic commands ###
