"""add_sync_expenses_days_back_to_settings

Revision ID: 300e46a3b3c6
Revises: d149dd90b38a
Create Date: 2025-12-24 16:42:28.370442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300e46a3b3c6'
down_revision: Union[str, None] = 'd149dd90b38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_settings', sa.Column('sync_expenses_days_back', sa.Integer(), nullable=False, server_default='60'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_settings', 'sync_expenses_days_back')
    # ### end Alembic commands ###
