"""add_expense_model_and_expense_linking

Revision ID: 6dda2710c840
Revises: dc2ccbe74e5c
Create Date: 2025-12-21 12:08:34.393669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dda2710c840'
down_revision: Union[str, None] = 'dc2ccbe74e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create new enums (expensestatusenum and expensepriorityenum)
    # Note: expensetypeenum already exists from budget_categories
    expensestatusenum = postgresql.ENUM(
        'DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'PAID', 'PARTIALLY_PAID', 'CANCELLED',
        name='expensestatusenum',
        create_type=False
    )
    expensepriorityenum = postgresql.ENUM(
        'LOW', 'NORMAL', 'HIGH', 'URGENT',
        name='expensepriorityenum',
        create_type=False
    )

    # Create enums if they don't exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expensestatusenum') THEN
                CREATE TYPE expensestatusenum AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'PAID', 'PARTIALLY_PAID', 'CANCELLED');
            END IF;
        END
        $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expensepriorityenum') THEN
                CREATE TYPE expensepriorityenum AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');
            END IF;
        END
        $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('expense_type', postgresql.ENUM('OPEX', 'CAPEX', name='expensetypeenum', create_type=False), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('contractor_name', sa.String(length=500), nullable=True),
    sa.Column('contractor_inn', sa.String(length=20), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'PAID', 'PARTIALLY_PAID', 'CANCELLED', name='expensestatusenum', create_type=False), nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT', name='expensepriorityenum', create_type=False), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('external_id_1c', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_contractor_id'), 'expenses', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_expenses_contractor_inn'), 'expenses', ['contractor_inn'], unique=False)
    op.create_index(op.f('ix_expenses_external_id_1c'), 'expenses', ['external_id_1c'], unique=True)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_is_active'), 'expenses', ['is_active'], unique=False)
    op.create_index(op.f('ix_expenses_number'), 'expenses', ['number'], unique=True)
    op.create_index(op.f('ix_expenses_organization_id'), 'expenses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_expenses_request_date'), 'expenses', ['request_date'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.add_column('bank_transactions', sa.Column('expense_id', sa.Integer(), nullable=True))
    op.add_column('bank_transactions', sa.Column('suggested_expense_id', sa.Integer(), nullable=True))
    op.add_column('bank_transactions', sa.Column('matching_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_index(op.f('ix_bank_transactions_expense_id'), 'bank_transactions', ['expense_id'], unique=False)
    op.create_foreign_key(None, 'bank_transactions', 'expenses', ['suggested_expense_id'], ['id'])
    op.create_foreign_key(None, 'bank_transactions', 'expenses', ['expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_bank_transactions_expense_id'), table_name='bank_transactions')
    op.drop_column('bank_transactions', 'matching_score')
    op.drop_column('bank_transactions', 'suggested_expense_id')
    op.drop_column('bank_transactions', 'expense_id')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_request_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_organization_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_number'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_is_active'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_external_id_1c'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_contractor_inn'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_contractor_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
