"""add_background_tasks_table

Revision ID: 2c1db3345c56
Revises: e05a1f0e0fae
Create Date: 2025-12-21 22:34:36.223786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1db3345c56'
down_revision: Union[str, None] = 'e05a1f0e0fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='backgroundtaskstatusenum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_tasks_id'), 'background_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_background_tasks_status'), 'background_tasks', ['status'], unique=False)
    op.create_index('ix_background_tasks_status_created', 'background_tasks', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_background_tasks_task_id'), 'background_tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_background_tasks_task_type'), 'background_tasks', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_background_tasks_task_type'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_task_id'), table_name='background_tasks')
    op.drop_index('ix_background_tasks_status_created', table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_status'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_id'), table_name='background_tasks')
    op.drop_table('background_tasks')
    # ### end Alembic commands ###
