#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Auto-Sync Settings Integration on Sync1CPage

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Get project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Docker for Redis
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Warning: Docker not found. Redis may not be available.${NC}"
fi

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js not found. Please install Node.js.${NC}"
    exit 1
fi

# Check Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: Python 3 not found. Please install Python 3.${NC}"
    exit 1
fi

echo -e "${GREEN}Prerequisites check passed${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Start Redis (required for Celery)
echo "Starting Redis..."
if docker ps | grep -q redis; then
    echo -e "${GREEN}Redis already running${NC}"
else
    docker-compose up -d redis 2>/dev/null || echo -e "${YELLOW}Warning: Could not start Redis via docker-compose${NC}"
fi

# Start Backend
echo "Starting Backend..."
cd "$PROJECT_ROOT/backend"
if [ -f ".env" ]; then
    source .env 2>/dev/null || true
fi
uvicorn app.main:app --reload --port 8005 &
BACKEND_PID=$!
cd "$PROJECT_ROOT"

wait_for_service 8005 "Backend"

# Start Frontend
echo "Starting Frontend..."
cd "$PROJECT_ROOT/frontend"
npm run dev &
FRONTEND_PID=$!
cd "$PROJECT_ROOT"

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:8005"
echo "  Frontend: http://localhost:3000"
echo "  API Docs: http://localhost:8005/docs"
echo ""
echo "Pages to verify:"
echo "  Sync1CPage:      http://localhost:3000/sync-1c"
echo "  SyncSettingsPage: http://localhost:3000/sync-settings"
echo ""
echo "Process IDs:"
echo "  Backend:  $BACKEND_PID"
echo "  Frontend: $FRONTEND_PID"
echo ""
echo "To stop: kill $BACKEND_PID $FRONTEND_PID"
echo ""
